environment:
  logger:
    path: ./conf/log4j.properties
    use: Y   # must set "Y" if you want to use
  envList:
    - env: prod
      execute:
        interval: 30000
        type: mysql 
      local:
        port: 3000
      remote:
        name: prodRemoteName
        host: prodRemoteHost
        port: 22
        key: prodRemoteKey
        mysql: 
          host: 127.0.0.1
          port: 3306
    - env: stg
      execute:
        interval: 30000
        type: command
      local:
        port: 3005
      remote:
        name: stgRemoteName
        host: stgRemoteHost
        port: 22
        key: stgRemoteKey
        command:
          line:
            - ls -al
            - pwd
            - lscpu
    - env: dev
      execute:
        interval: 60000
        type: command
      local:
        port: 3010
      remote:
        name: devRemoteName
        host: devRemoteHost
        port: 22
        key: devRemoteKey
        command:
          line:
            - ls -al
            - pwd
            - lscpu