environment:
  envList:
    - env: prod
      local:
        port: 3000
      remote:
        host:
        port:
        key:
      mysql:
        host:
        port:
        id:
        pwd:
    - env: stg
      local:
        port: 3005
      remote:
        host:
        port:
        key:
      command:
        line:  
      
    