environment:
  envList:
    - env: prod
      local:
        port: 3000
      remote:
        host: 1
        port: 22
        key: 1
      mysql:
        host: 127.0.0.1
        port: 3306
        id: 1
        pwd: 1
    - env: stg
      local:
        port: 3005
      remote:
        host: 1
        port: 22
        key: 1
      command:
        line:
          - ls -al
          - pwd
          - lscpu
      deph1:
        dephth2:
          pethi: ttt
      
    
