environment:
  envList:
    - env: prod
      execute:
        interval: 60000
        type: mysql 
      local:
        port: 3000
      remote:
        host: prodHostName
        port: 11
        key: ./conf/private_key/private_key.ppk
        mysql: 
          host: prodMysqlHost
          port: 3306
          id: prodMysqlId1
          pwd: prodMysqlPwd2
          pp:
    - env: stg
      execute:
        interval: 60000
        type: mysql
      local:
        port: 3005
      remote:
        host: stgHostName
        port: 22
        key: ./conf/private_key/private_key.ppk
        mysql: 
          host: prodMysqlHost
          port: 3306
          id: prodMysqlId1
          pwd: prodMysqlPwd2
      command:
        line:
          - ls -al
          - pwd
          - lscpu
    - env: dev
      execute:
        interval: 60000
        type: command
      local:
        port: 3010
      remote:
        host: devHostName
        port: 22
        key: ./conf/private_key/private_key.ppk
      command:
        line:
          - ls -al
          - pwd
          - lscpu
      
    
