environment:
  envList:
    - env: prod
      local:
        port: 3000
      remote:
        host: ssh.ap-3.magento.cloud
        port: 22
        key: ./conf/private_key/private_key.ppk
      mysql:
        host: 127.0.0.1
        port: 3306
        id: cbao65gdzs564_stg
        pwd: VRGtSHDApCvPid2
    - env: stg
      local:
        port: 3005
      remote:
        host: ssh.ap-3.magento.cloud
        port: 22
        key: ./conf/private_key/private_key.ppk
      command:
        line:
          - ls -al
          - pwd
          - lscpu
      
    